var headerText = "Polizeiterror-Bingo";

var footerText = "<a href='https://github.com/id101010/HTML5-bingo/' target='_blank'>This versions is code available on github</a><br/><a href='https://github.com/jeffehobbs/HTML5-bingo/' target='_blank'>Original code</a>";

var winText = "Gratulation, du wirst verhaftet.";

var clickSnd = new Audio("audio/click.mp3");

var winSnd = new Audio("audio/win.mp3");

var JSONBingo = {"squares": [
          {"square":"Anschlag von Morges"},
          {"square":"Gesinnung bleibt nach Strafe"},
          {"square":"Ausschaffung"},
          {"square":"Jihad"},
          {"square":"Radikalisierte Kolleg*innen"},
          {"square":"Das Internet ist schuld!"},
          {"square":"Sinnvolle Massnahmen"},
          {"square":"Kinderrechte werden gewahrt"},
          {"square":"PMT schliesst L&uuml;cke im Gesetz!"},
          {"square":"Handeln bevor es zu sp&auml;t ist!"},
          {"square":"Verhinderung terroristischer Aktivit&auml;ten!"},
          {"square":"Das Gesetz ist EMRK-Konform!"},
          {"square":"Im Ausland gibts &auml;hnliche Massnahmen!"},
          {"square":"Gef&auml;hrder*innen- Begriff ist klar definiert"},
          {"square":"Gef&auml;hrder*innen missachten Rechtsstaat"},
          {"square":"Erh&ouml;hung der Bev&ouml;lkerungs- sicherheit!"},
          {"square":"Rechtsstaatlichkeit ist gew&auml;hrleistet!"},
          {"square":"Gef&auml;hrder*innen waren polizeibekannt"},
          {"square":"Gef&auml;hrder*innen wurden &uuml;berwacht"},
          {"square":"Gef&auml;hrder*innen waren auf Terrorliste"},
          {"square":"Gewalt, Angst und Schrecken"},
          {"square":"Massnahmen je nach Situation!"},
          {"square":"Psychologische Betreuung zur Pr&auml;vention"},
          {"square":"Besch&auml;ftiguns- programme zur Pr&auml;vention"},
          {"square":"Radikalisierung!"},
          {"square":"Geheimdienst muss mehr Befugnisse erhalten!"},
          {"square":"Sch&auml;rfere Gesetze!"},
          {"square":"Vorratsdaten- speicherung"},
          {"square":"Moscheen"},
          {"square":"Pr&auml;ventiv"},
          {"square":"In eine Menschenmenge fahren"},
          {"square":"Staatliche Ordnung beeinflussen"},
          {"square":"Grundrechte werden nicht verletzt"},
          {"square":"Hausarrest nur durch Gerichtsbeschluss!"},
          {"square":"Massnahmen k&ouml;nnen angefochten werden"},
          {"square":"Gewaltenteilung wird respektiert!"},
          {"square":"Demokratische und rechtsstaatliche Grundlagen"},
          {"square":"Keine einschneidenden Massnahmen"},
          {"square":"Vorbereitungshandlungen"},
          {"square":"Syrien!"},
          {"square":"Innere Sicherheit"},
          {"square":"D&uuml;nger beschaffen"},
          {"square":"Schutz der Freiheitsrechte"},
          {"square":"Immigration!"},
          {"square":"Killerspiele!"},
          {"square":"Nachrichtendienst -gesetz"},
          {"square":"Nachrichtendienst des Bundes"},
          {"square":"IS-Propaganda konsumieren"},
          {"square":"Paris, Berlin oder Wien"},
          {"square":"FEDPOL"},
          {"square":"Bewegungsfreiheit einschr&auml;nken"},
          {"square":"Radikale Prediger"},
          {"square":"Noch keine Straftat begangen"},
          {"square":"Terroristische Atkivit&auml;ten"},
          {"square":"Terrorrekrutierung"},
          {"square":"Terroristen haben verschl&uuml;sselt"},
          {"square":"Terrorwarnung aus nur einer Quelle"},
          {"square":"Islamistischer Hintergrund"},
          {"square":"In letzter Sekunde verhindert"},
          {"square":"Datenschutz ist Terroristenschutz"},
          {"square":"Privacy ist Schuld!"},
          {"square":"Straftaten und Gewalt"},
          {"square":"Kontaktverbot zu radikalisierten Gruppen"},
          {"square":"Aus Mangel an Beweisen freigelassen"},
          {"square":"Verschl&uuml;sselung verhindert Strafverfolgung"},
          {"square":"Snowden ist Schuld!"},
          {"square":"Mehr Befugnisse f&uuml;r die Dienste"},
          {"square":"Mehr Befugnisse f&uuml;r die Polizei"},
          {"square":"Salafisten"},
          {"square":"Die Grenzen zu!"},
          {"square":"Wir brauchen mehr &Uuml;berwachung!"},
          {"square":"SVP ist daf&uuml;r"},
          {"square":"FDP ist daf&uuml;r"},
          {"square":"Freiheit durch Sicherheit"},
          {"square":"Geheimdienst- Quellen"},
          {"square":"Koran"},
          {"square":"Hooligans!"},
          {"square":"Fahne gefunden"},
          {"square":"Datenbanken zusammen- f&uuml;hren"},
          {"square":"Gegner*innen sind linksversiffte Zecken"},
          {"square":"Keine Willk&uuml;r!"},
          {"square":"Nur mit konkreten Hinweisen!"},
      ]
};
